version: '3'
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=judgeapi
      - POSTGRES_PASSWORD=judgeapi
      - POSTGRES_DB=judgeapi-dev
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=codingblocks
      - RABBITMQ_DEFAULT_PASS=codingblocks
    ports:
      - "5672:5672"
      - "15672:15672"
  api:
    build: .
    image: codingblocks/judge-api
    volumes: 
      - ./coverage:/usr/src/judge-api/coverage
    depends_on:
      - postgres
    ports:
    - "3737:3737"
    env_file:
      - test.env
    command: ./scripts/wait-for-it.sh -t 180 postgres:5432 -- ./scripts/wait-for-it.sh -t 180 rabbitmq:5672 -- npm run cover      
