version: 2
machine:
  services:
    - docker
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.9
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.17.1/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Build Docker Image
          command: |
            docker-compose --file docker-compose-test.yml build
      - run:
          name: Run Test Docker Compose
          command: |
            docker-compose --file docker-compose-test.yml up --abort-on-container-exit
      - run:
          name: Submit Code Coverage
          command: bash <(curl -s https://codecov.io/bash)

